language: php
sudo: false
cache:
  apt: true
  directories:
  - "$HOME/.composer/cache"
  - "$HOME/.cache/bin"
  - "$HOME/.n98-magerun/modules"
  - "$HOME/.cache/magento"
php:
- 5.5
- 5.6
- 7.0
matrix:
  fast_finish: true
  allow_failures:
  - php: 5.6
    env: MAGENTO_VERSION=ce-1.8.1.0
  - php: 7.0
    env: MAGENTO_VERSION=ce-1.8.1.0
env:
  global:
  - APPNAME=Ffuenf_ProductAlertCleaner
  - secure: vlu22zy0mKEpLg9mkR9DfQKo/+7TP3M/42T78yFWl3qeCiCGgRARhosJzMenywQx4lF8qShcIjaJ4oRXzIqmigbgzGFjdkJ0BjQxV8CYJ/8lWgRP1imq+c1lbKBlKJ12Oxm+FZx/UOW3xXI7KiURe6dLnDVjqdQ/7dx3cE2YsA8Ozbh4I0l6rTv3/1nohvxTaP9pSElNFCCuDJ/THFEFYAnMAxf1YEJ+mbmFsZmIHVIAjl8mVUG4osxZEWi16SSldHZO5qT2E+HCXBSV/MUA0EpkM5Cb+ORmJkeeN6l6Pb8aw5zqqeH5WFsRARZ+XNUp3TMS4PW7XIitjJkuG4atwZyw4vFCeF9ZoOWthKWeoTGlgejQEzdaoVYFACB8BB6rE9WKvKFxt/aV6lWfib0jJLYgLU+YXm0Bm+DKbOiPAEvSj1oFX86BGd9G5o9KwkL6n5/VJhtoZLsTM4owOj4H+ibrCXSxI4KHUwwH7v0P+52ZLLyFohLKTObWqA+N5JSYOwNz64Pj8FeIVtJaEXgL6K7JQ8h7M61csJKSuBZQdZOocPTJC+i1Xblr0il+LIp14Nl82bZATwcxaJVMaMXLezH5i5joUl5sUNlliK7uWSt+zcyqvgHolghpjHEeTJLk9ZcJ7KkBo+asJQ0ch97SyFlDt/yd+Ep4k5KUqk1/mmk=
  - secure: PaMfgpKRa9NjW8cMlcg+KvGkiXYaomvJNPePO8E+u1HxEteQ+W6MuoPOUUnetfRrAYelsSAwDiL0wgKzTPTMzp1RAoiYIf4//tVWekN8i45OTSJZl76Hz4e5WuqOFYVwXdBvR8F2kBtnz/LiqvaQwA6EjAwrR3WYweccIj1mO1NTeOqPr4ZKwyk5SAfupB2zxETcSRdRPU0/hEk/2sYAh0hYC5fap4HcXg+kNo3ENyQcXAYPyJsFnY9P9PtJ0GP+AqxTgMbUPmyLp0Eeja+cDv9ZVRs5lmeBLgX0rMUppUVafJOKbhOj65kSCrzO6eHqY2Riry9LQr9IUG5rSYt64qL46jJeyf/Zh6daJE+g6E9fMN57F2ZTQ7e9HMFir9HiXbvgw5Y4RjYOIzAcIaijpzePn6PCN0SnMDjw7Xs1mo5YGnitaAyn+TnQinyULdy3R38Wg8s3OXz75nBDQ1au924JF4TwVXCKXv6JL/qpkQ/1YZspoAssljzbU4khhV7XdDBv7o1b7y2jz7N0AsIP4dZfOEqvBaC+ZBjD2SQTM9UvIdpiUmaUgN8DLi9scNMvs48u4ThEe/D743eki+wu+SoLwcZeg7pHib6X/bd4Psa45sU+7UOYcGqFlvlCxk/pOYMTYOSynXeSs1viVzXMlsh7iKBKSdlv8kVWyiQKa8A=
  - secure: J38w5fR80HTq8bJXuarClYL4fWEHbvjYqqrA7iF6o0dC9S+YUC6j/Kvvi+r226NhZ0uet9NDel7+JcNF5IupBEBHGoX5JoVA3bs1IUzY9nc/FvdW98CRXFkgzwtKOwKelVuQTgBvP9io2tLk2XGZ2qkZUaWhZ6zfG2uSYTezl0xCvWq4u4QwBv0toY4N7pPfRJI/BpUW3UVGK1Dt7dofAArxMlmAMekv/1/GI3917nejscxccSLXyWwTDG6KjAQDMwS2VkuFaLc1CnVMKAd86dbUn5Y7Bptwvfs0ykc2i6djDWrTtiekPxaJnq7ZLezTn1GgH/tCIDIs05sH25xaeqvBfKy+/00StlBLlSKzoUQvHlGz8eqY5eF66Q4lSuNcMHfOpjetshgUY8mzSFSZHHamtXZmgCrkvLOhgdkPB35SEVH/xdecCMsHLfBiv6hlQwqDmEFyRzsBwooACUw2J7ElTAVIX3BluGYgFTWrqyOglRousVNNeYf+bEiAPE5ujDB1OqBwlXnbDfDmLGpGsakbYeLnuxuSriHkr5u2NAKOZbyImF9KZCZMAN3OFlwjVHVBrrQe9+jeat4m1D5SKaVWkvP06uDHnLDx1gHA1TG/zmkXPJyme4rPb3kjDjh6JozgnGkDVy27FZaB/5GG6z57RZ1El0CkxeL4aYwNiSE=
  matrix:
  - MAGENTO_VERSION=ce-1.9.2.4
  - MAGENTO_VERSION=ce-1.9.1.1
  - MAGENTO_VERSION=ce-1.8.1.0
  - MAGENTO_VERSION=ce-1.7.0.2
  - MAGENTO_VERSION=ce-1.6.2.0
before_install:
- curl -sSL https://raw.githubusercontent.com/ffuenf/MageTestStand/master/before_install.sh
  | bash
script:
- curl -sSL https://raw.githubusercontent.com/ffuenf/MageTestStand/master/script.sh
  | bash
deploy:
  provider: releases
  file:
  - "${APPNAME}-${TRAVIS_TAG}.zip"
  - "${APPNAME}-${TRAVIS_TAG}.tar.gz"
  skip_cleanup: true
  on:
    branch: master
    tags: true
  api_key:
    secure: c07he9mR57KJ4Syw8FQxgNbnoAeIuEOh7yQjjcoyVAwzPQj/AfFN7GkXoaxSUW5DxpCnooFP0N8BQwRbCS8uiHq2OJmOFn72cVw1P4lPgNU4EDS/ItRBJdeIQXouJjXh+R+MOhxjMz4uZVFrEYiGlC8k4Hr+RZPNWierMQgZhU47xwXeOArOr25MgITtKcBZrF5NyITyTOR4RjucBtyJVkARP4DYyagcQ1F8SXzy9LQl9IT1wtmsNExG6RN7m7u9peX0YC+Cph74LCMBXcC4trJiLTDof8PAAn5SBkYKXq93QS2Xn5kw3sLECtZfMF/0s+1KTppD4NSFIGdEGLxVUfC1R0wt5mRHQ6xd396EfNX+OmPhyCTfw9oXxH0CmZaLz+zzWL9Q/VzhpzITsQQ2FP7gnImHTkrONgCXFEPDigXi+rrPablvyoK3RSvUvOZKKO1iLChQu/NLl4GfsjmifCvt2YJriREsm9o+xUv2DcDGPAJLblJEHGNbNTlVFrfbxFoqGPjqvfz2zzzMFHWnzSYmWAZgh049G2HywumGxcPlXhMFviKVXtTsD0zDedkjCMBkqYdClT8+a7nO4ewCRjZTI2lYrPF8fk5BpJPLVLKfF5IsNdfRI27nHEq/tVAwhBNBZ/zirmpl03xI/P+IIt6bMjIsScJT8Z01DiMTbXc=
notifications:
  slack:
    secure: jnl97CrjPgceNlEWnKo+HJslQ82N7+cQn/tFZjMmUW7LsaTsPzyf2hxzTjQxdUU4gTT9VF3qcr6BqU17RmoKMYKUVxsVPnKGynrMZb/VnYBirOOmJ5P+cENtEKkBhDabfvi6wN5Qx3lYPjrqgRR0BVDMcCc1yPEtg69Un1v5jBkIF/cPPy7B1NM1nGe1XLd18Lnfr8BP2MgSO5I2ZZSf2eW1nbTibl2dpCBFmrUrkHsHbftMkjOBUiE/gxfndFA8tP622qaP+U0FXi3KC9RnDEDYd1QO30aT9R2ypRVpzyzkmdYSxo/UBJTptOUmSEayrWQUyiDbx2URDSSeKIEGYW5a43oqksTItZ7j5E+ERb4dMgo2c0YIDefOBjh9tvBz/dl4C8KY2Z6mGdVT7h5wJmpLfQtG+kM2BEXGRynjqZQkOQ10NFWLe8rL0uzyWC1xx1cPabzXfzu9hETKyiq0Pdm6nufFdyLxBM63mNA7f4P2Qt41oGcHECSWs3wV8LOkQRb4UlOWxG5HftDtM62oap1nt8mg+0JMR8W2yNl081dbMP2kWaonHVotLWxDxE+gvkKcV5PsNJD+oWYgsOCKEeL94NQSg5BVTLuFazRNovWZMYnXhxjG4uFBMjg9lA46ACtdzl6auCa9L2hBxdtq+8PAEQAYbos5bXqvkbLcq3I=
